language: node_js
node_js:
  - 0.4
  - 0.6
  - 0.8

services:
  - mongodb

before_script:
  - mongo mydb_test --eval 'db.addUser("test", "test");'

notifications:
  irc: "irc.freenode.org#observe.it"
